# DFS / BFS

In [1]:
def timer(func):
    import time
    def wrapper(*args, **kwargs):
        start = time.time()
        func(*args, **kwargs)
        end = time.time()
        print('{:.10f}'.format(end - start))
    return wrapper

## Stack

In [2]:
stack = []
stack.append(1)
stack.append(2)
stack.append(3)

print(stack.pop())
stack

3


[1, 2]

## Queue

In [3]:
from collections import deque

queue = deque()
queue.append(1)
queue.append(2)
queue.append(3)

print(queue.popleft())
queue

1


deque([2, 3])

## Recursive

In [9]:
def comparison(n):
    assert n > 0
    import time
    
    def factorial_iterative(n):
        result = 1
        for i in range(1, n + 1):
            result *= i
        return result
    
    start = time.time()
    print('iterative', factorial_iterative(n))
    end = time.time()
    print('{:.10f}'.format(end-start))
    
    def factorial_recursive(n):
        if n <= 1:
            return 1
        return n * factorial_recursive(n - 1)
    
    start = time.time()
    print('recursive', factorial_recursive(n))
    end = time.time()
    print('{:.10f}'.format(end-start))
    
comparison(10)

iterative 3628800
0.0000000000
recursive 3628800
0.0000000000


# DFS : 깊이 우선 탐색

## 인접 행렬
- 메모리 비효율
- 조회가 빠름

In [11]:
inf = 987654321
graph = [[0, 7, 5], 
         [7, 0, inf],
         [5, inf, 5]]
print(np.array(graph))

[[        0         7         5]
 [        7         0 987654321]
 [        5 987654321         5]]


## 인접 리스트
- 메모리 효율
- 조회가 느림

In [17]:
graph = [[] for _ in range(3)]

graph[0].append((1, 7))
graph[0].append((2, 5))

graph[1].append((0, 7))

graph[2].append((0, 5))

print(graph)

[[(1, 7), (2, 5)], [(0, 7)], [(0, 5)]]


In [29]:
def dfs(graph, v, visited):
    visited[v] = True
    print(v, end=' ')

    for i in graph[v]:
        if not visited[i]:
            dfs(graph, i, visited)

graph = [
    [],
    [2, 3, 8],
    [1, 7],
    [1, 4, 5],
    [3, 5],
    [3, 4],
    [7],
    [2, 6, 8],
    [1, 7]
]

visited = [False] * 9

print(dfs(graph, 1, visited))

1 2 7 6 8 3 4 5 None


# BFS : 너비 우선 탐색

In [31]:
from collections import deque

def bfs(graph, start, visited):
    queue = deque([start])
    visited[start] = True
    
    while queue:
        v = queue.popleft()
        print(v, end=' ')
        for i in graph[v]:
            if not visited[i]:
                queue.append(i)
                visited[i] = True
                
graph = [
    [],
    [2, 3, 8],
    [1, 7],
    [1, 4, 5],
    [3, 5],
    [3, 4],
    [7],
    [2, 6, 8],
    [1, 7]
]

visited = [False] * 9

bfs(graph, 1, visited)

1 2 3 8 7 4 5 6 

## 음료수 얼려먹기

In [3]:
input1 = '''00110
00011
11111
00000'''

input2 = '''00000111100000
11111101111110
11011101101110
11011101100000
11011111111111
11011111111100
11000000011111
01111111111111
00000000011111
01111111111000
00011111111000
00000001111000
00000001111000
11111111110011
11100011111111
11100011111111'''

In [151]:
@timer
def dfs(input1):
    graph = [list(map(int, row)) for row in input1.split('\n')]
    n = len(graph)
    m = len(graph[0])
    visited = [[False] * m for _ in range(n)]

    def dfs(x, y, visited):
        if x < 0 or y < 0 or x >= n or y >= m:
            return False
        if not visited[x][y] and graph[x][y] == 0:
            visited[x][y] = True
            dfs(x + 1, y, visited)
            dfs(x - 1, y, visited)
            dfs(x, y + 1, visited)
            dfs(x, y - 1, visited)
            return True
        return False

    cnt = 0
    for i in range(n):
        for j in range(m):
            if dfs(i, j, visited):
                cnt += 1
    print(cnt)
dfs(input1)
dfs(input2)

3
0.0000000000
8
0.0000000000


In [152]:
@timer
def solution(input1):
    graph = [list(map(int, row)) for row in input1.split()]
    N = len(graph)
    M = len(graph[0])

    def dfs(x, y):
        # 좌표를 벗어날 경우 False를 반환
        if x < 0 or y < 0 or x > N - 1 or y > M -1:
            return False
        if graph[x][y] == 0:
            # 방문처리 시 True를 반환하여 클러스터 한 개당 하나의 카운트
            graph[x][y] = 1
            # 재귀적 탐색 -> 주변을 모두 방문처리
            dfs(x - 1, y)
            dfs(x + 1, y)
            dfs(x, y - 1)
            dfs(x, y + 1)
            return True
        # 방문했던 곳은 False를 반환하여 카운트하지 않도록 함
        return False

    cnt = 0

    for i in range(N):
        for j in range(M):
            if dfs(i, j):
                cnt += 1
    print(cnt)
    
solution(input1)
solution(input2)

3
0.0000000000
8
0.0009756088


## 미로 탈출

In [11]:
input1 = '''5 6
101010
111111
000001
111111
111111'''

In [167]:
from collections import deque

graph = [list(map(int, row)) for row in input1.split('\n')[1:]]
n, m = list(map(int, input1.split('\n')[0].split()))
visited = [[False] * m for _ in range(n)]

#상 하 좌 우
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]


queue = deque()
queue.append((0, 0))

while queue:
    x, y = queue.popleft()
    visited[x][y] = True
    for i in range(4):
        nx = x + dx[i]
        ny = y + dy[i]
        if nx < 0 or ny < 0 or nx >= n or ny >= m:
            continue
        if not visited[nx][ny] and graph[nx][ny] == 1:
            queue.append((nx, ny))
            graph[nx][ny] = graph[x][y] + 1
graph[n - 1][m - 1]

10

In [128]:
from collections import deque


n = int(input1.split()[0])
m = int(input1.split()[1])
graph = [list(map(int, row)) for row in input1.split()[2:]]

# 상 하 좌 우
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]

def bfs(x, y):
    queue = deque()
    queue.append((x, y))
    while queue:
        x, y = queue.popleft()
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            if nx < 0 or ny < 0 or nx >= n or ny >= m:
                continue
            if graph[nx][ny] == 0:
                continue
            # 해당 노드 상하좌우에 거리를 계산하여 입력
            if graph[nx][ny] == 1:
                graph[nx][ny] = graph[x][y] + 1
                queue.append((nx, ny))

    return graph[n - 1][m - 1]

print(bfs(0, 0))

10


In [156]:
input1 = '''5 6
101010
111111
000001
111111
111111'''

In [179]:
n = int(input1.split()[0])
m = int(input1.split()[1])
graph = [list(map(int, row)) for row in input1.split()[2:]]
visited = [[0] * m for _ in range(n)]

x, y = 0, 0

# 상 하 좌 우
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]

results = []
def bfs(x, y):
    queue = deque()
    queue.append((x, y))
    results = []
    while queue:
        x, y = queue.popleft()
        visited[x][y] = 1
        for i in range(4):
            nx = x + dx[i]
            ny = y + dy[i]
            if nx < 0 or ny < 0 or nx >= n or ny >= m:
                continue
            if graph[nx][ny] == 1 or visited[nx][ny] == 0:
                queue.append((nx, ny))
                graph[nx][ny] = graph[x][y] + 1
                if graph[n - 1][m - 1] != 1 and graph[n - 1][m - 1] not in results:
                    results.append(graph[n - 1][m - 1])

    return min(results)

print(bfs(x, y))

10


# bfs와 dfs

- 그래프를 DFS로 탐색한 결과와 BFS로 탐색한 결과를 출력하는 프로그램을 작성하시오. 단, 방문할 수 있는 정점이 여러 개인 경우에는 정점 번호가 작은 것을 먼저 방문하고, 더 이상 방문할 수 있는 점이 없는 경우 종료한다. 정점 번호는 1번부터 N번까지이다.
- 첫째 줄에 정점의 개수 N(1 ≤ N ≤ 1,000), 간선의 개수 M(1 ≤ M ≤ 10,000), 탐색을 시작할 정점의 번호 V가 주어진다. 다음 M개의 줄에는 간선이 연결하는 두 정점의 번호가 주어진다. 어떤 두 정점 사이에 여러 개의 간선이 있을 수 있다. 입력으로 주어지는 간선은 양방향이다.

In [2]:
input1 = '''4 5 1
1 2
1 3
1 4
2 4
3 4'''
input2 = '''5 5 3
5 4
5 2
1 2
3 4
3 1'''
input3 = '''1000 1 1000
999 1000'''

In [124]:
def solution(input1):
    from operator import itemgetter

    n, m, v = list(map(int, input1.split('\n')[0].split()))
    graph = [list(map(int, row.split())) for row in input1.split('\n')[1:]]
    graph += graph + [list((e, s)) for s, e in graph]
    graph.sort(key=itemgetter(1))

    visited = [False] * (n + 1)
    
    print(v, end=' ')
    def dfs(graph, v, visited):
        visited[v] = True
        for s, e in graph:
            if v == s and visited[e] == False:
                print(e, end=' ')
                dfs(graph, e, visited)

    dfs(graph, v, visited)
    print('\n')
    def bfs(input1):
        from collections import deque

        n, m, v = list(map(int, input1.split('\n')[0].split()))
        graph = [list(map(int, row.split())) for row in input1.split('\n')[1:]]
        graph = graph + [list((e, s)) for s, e in graph]
        graph.sort(key=itemgetter(1))

        visited = [False] * (n + 1)

        queue = deque()
        queue.append(v)

        visited[v] = True
        print(v, end=' ')
        while queue:
            x = queue.popleft()
            for s, e in graph:
                if x == s and visited[e] == False:
                    print(e, end=' ')
                    queue.append(e)
                    visited[e] = True
    bfs(input1)
    print('\n')

print('#Q1')
solution(input1)
print('#Q2')
solution(input2)
print('#Q3')
solution(input3)

#Q1
1 2 4 3 

1 2 3 4 

#Q2
3 1 2 5 4 

3 1 4 2 5 

#Q3
1000 999 

1000 999 



# 단지번호 붙이기
<그림 1>과 같이 정사각형 모양의 지도가 있다. 1은 집이 있는 곳을, 0은 집이 없는 곳을 나타낸다. 철수는 이 지도를 가지고 연결된 집의 모임인 단지를 정의하고, 단지에 번호를 붙이려 한다. 여기서 연결되었다는 것은 어떤 집이 좌우, 혹은 아래위로 다른 집이 있는 경우를 말한다. 대각선상에 집이 있는 경우는 연결된 것이 아니다. <그림 2>는 <그림 1>을 단지별로 번호를 붙인 것이다. 지도를 입력하여 단지수를 출력하고, 각 단지에 속하는 집의 수를 오름차순으로 정렬하여 출력하는 프로그램을 작성하시오.
- 첫 번째 줄에는 지도의 크기 N(정사각형이므로 가로와 세로의 크기는 같으며 5≤N≤25)이 입력되고, 그 다음 N줄에는 각각 N개의 자료(0혹은 1)가 입력된다.

In [97]:
input1 = '''7
0110100
0110101
1110101
0000111
0100000
0111110
0111000'''

In [100]:
n = int(input1.split()[0])
graph = [list(map(int, row)) for row in input1.split('\n')[1:]]
visited = [[False] * n for _ in range(n)]

# 상 하 좌 우
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]

def dfs(x, y):
    global n_neighbors

    if x < 0 or x >= n or y <0 or y >= n:
        return False, n_neighbors
    
    if graph[x][y] == 0 or visited[x][y] == True:
        return False, n_neighbors
    
    visited[x][y] = True
    n_neighbors += 1
    for i in range(4):
        nx = x + dx[i]
        ny = y + dy[i]
        dfs(nx, ny)
    return True, n_neighbors

cnt = 0
num = []

for i in range(n):
    for j in range(n):
        n_neighbors = 0
        result = dfs(i, j)
        cnt += int(result[0])
        if result[1] != 0:
            num.append(result[1])

num.sort()

print(cnt)
for n in num:
    print(n)

3
7
8
9
